#!/bin/bash
#lidarpath=/home/eivindf/cases/SKIRON_HDF5_V
SUBFOLDER=cappifiles/Cap420.cappi
SUBFOLDER=azifiles
lidarpath=$HOME/results/lidar/Frankfurt/$SUBFOLDER
folderName=$HOME/results/lidar/Frankfurt/$SUBFOLDER
pushd $folderName > /dev/null
#filetypes="azi ele vol"
filetypes="azi"
#filetypes="cappi"
#dateStringss="2020-11-06"
dateStringss="2021-07-10"
#dateStringss="2020-11-05 2020-11-06 2020-11-10 2020-11-11 2020-11-21 2020-12-04 2020-12-05"
RUN_DAYS=1
if [[ $1 == 1 ]]
then
    for dateStrings in $dateStringss
    do
        for filetype in $filetypes
        do
            #pvdfilename="$filetype.pvd"
            pvdfilename="$dateStrings.pvd"
            echo -e "<VTKFile type=\"Collection\">" > $pvdfilename
            START_SIM_DATE="$dateStrings 12:00:00"
            current_epoch=$(date -u +'%s' --date="$START_SIM_DATE UTC")
            echo -e "\t<Collection>" >> $pvdfilename
            i=0
            #mkdir -p $filetype.pvd-data
            mkdir -p $dateStrings.pvd-data
            for ((j=0; j<$RUN_DAYS; j++))
            do
                dateString=$(date -u +'%Y-%m-%d' --date="$START_SIM_DATE UTC + $j days")
                mkdir -p $dateString
                #cp $lidarpath/$dateString/*.$filetype.h5 $dateString
                fileNames=$(ls $dateString/*.$filetype.h5)
                for filename in $fileNames
                do
                    dateStringStrip=${dateString//-}
                    temp="${filename##*$dateString}"
                    temp="${temp##*$dateStringStrip}"
                    time=$dateStringStrip${temp:0:8}
                    START_SIM_DATE="${time:0:4}-${time:4:2}-${time:6:2} ${time:8:2}:${time:10:2}:${time:12:2}"
                    echo $START_SIM_DATE
                    target_epoch=$(date -u +'%s' --date="$START_SIM_DATE UTC")
                    t=$(( $target_epoch - $current_epoch ))
                    vtuFilename=${pvdfilename}-data/data-${i}.vtu
                    vtuFileName=${pvdfilename}-data/data-${i}-1.vtu
                    siso -f vtu $filename $vtuFilename --coords utm:32u 
                    echo -e "\t\t<DataSet timestep=\"$t\" part=\"0\" file=\"${vtuFileName}\" />" >> $pvdfilename
                    i=$(( i + 1 ))
                done
            done
            echo -e "\t</Collection>" >> $pvdfilename
            echo -e "</VTKFile>" >> $pvdfilename
        done 
    done
fi
if [[ $2 == 1 ]]
then
    for dateStrings in $dateStringss
    do
        START_SIM_DATE="$dateStrings 12:00:00"
        pvdfilename="$dateStrings.pvd"
        current_epoch=$(date -u +'%s' --date="$START_SIM_DATE UTC")
        WRF_FOLDER="${dateStrings//-}"12
        SED_VARIABLES="current_epoch pvdfilename WRF_FOLDER SUBFOLDER"
        DICTS="lidarValidation.py"
        cp $HOME/kode/wrfStudies/lidarValidation.py .
        source $HOME/kode/bashScripts/sedFiles
        #pushd $HOME/results/WRF/Frankfurt/$WRF_FOLDER > /dev/null
        #siso -f pvd wrfout_d04.nc wrfout_d04_vol.pvd --coords utm:32u -l P,T,U,V,W
        #popd > /dev/null
        #/usr/lib/ParaView-5.8.1-osmesa-MPI-Linux-Python3.7-64bit/bin/pvbatch lidarValidation.py
        #pvbatch lidarValidation.py
        paraview --script=lidarValidation.py
    done
fi


if [[ $3 == 1 ]]
then
    ALLDATES="${dateStringss//-}"
    ALLDATES="${ALLDATES// /12.ogv|}"
    ffmpeg -i "concat:${ALLDATES}12.ogv" -codec copy lidarValidation.ogv
fi
popd > /dev/null
if [[ $4 == 1 ]]
then
    folders=$(ls $lidarpath )
    for folder in $folders
    do
        echo "Number of $filetype files in folder "$folder
        find $lidarpath/$folder -mindepth 1 -type f -name "*.$filetype.h5" -printf x | wc -c
    done
fi
#siso -f pvd las01_fra_lidar_skiron_2020101123554000V.vol.h5 --coords utm:32u
#python ~/kode/wrfStudies/plotComparison.py --sourceid Frankfurt --startdate "2020-10-11 12:00:00" --enddate "2020-10-12 12:00:00" --ploterror
