#!/bin/bash
MODEL_NAME="ZEBLAB"
#MODEL_NAME="tutorial"
NP=4    	# Number of processors
name=${1:-$MODEL_NAME}
if [ -z "$DISPLAY" ]
then
	echo "Error: set the DISPLAY variable" #The display variable should be set for post processing purposes in paraview. This issue arises when using screen, and can be resolved by first getting the display variable outside the screen session (echo $DISPLAY) and then inside the screen session setting the variable to this value (i.e. export DISPLAY=localhost:10.0)"
fi

DICTS="namelist.wps"

SED_VARIABLES="INTERVAL_SECONDS REF_LAT REF_LON STAND_LON GEOG_DATA_PATH MAX_DOM"
MESH_ARR=$(seq 1 1)
for MESH in $MESH_ARR
do
	source ./parameters
	pathToFolder="$WRFDIRECTORY/Build_WRF/WPS"
	cp namelist_$MODEL_NAME.wps $pathToFolder/namelist.wps
	cp plotgrids_new.ncl wrf_wps_ter.ncl $pathToFolder/util
	
#	#pushd $WRFDIRECTORY/Build_WRF/DATA > /dev/null
#	#echo "Downloading NCEP data ... "
#	#$HOME/kode/bashScripts/getNCEPdata "20200721" "00 03 06"
#	#popd > /dev/null
#
	pushd $pathToFolder > /dev/null
	source $HOME/kode/bashScripts/sedFiles
	if [[ 1 ]]
	then
		rm -f FILE* met_em*
		./geogrid.exe | tee log.geogrid
		ncl util/plotgrids_new.ncl # Plot domains
		ncl util/wrf_wps_ter.ncl # Plot terrains
		./link_grib.csh $WRFDIRECTORY/Build_WRF/DATA/GFS*
		ln -sf ungrib/Variable_Tables/Vtable.GFS Vtable
		./ungrib.exe
		./metgrid.exe | tee log.metgrid
	fi
	
	popd > /dev/null
	
	pathToFolder="$WRFDIRECTORY/Build_WRF/WRF/run"
	cp namelist_$MODEL_NAME.input $pathToFolder/namelist.input
	pushd $pathToFolder > /dev/null
	DICTS="namelist.input"
	source $HOME/kode/bashScripts/sedFiles
	rm -f met_em* wrfout*
	ln -sf ../../WPS/met_em* .	
	mpirun -np 1 ./real.exe
#	ncl ../var/graphics/ncl/wrf_Surface1.ncl
	#ncl ../var/graphics/ncl/wrf_Surface2.ncl
	#ncl ../var/graphics/ncl/wrf_Surface3.ncl
	popd > /dev/null
done
